apiVersion: "v1"
kind: ConfigMap
metadata:
  name: postgresql-service
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: "10.100.126.192"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==